"""Application settings loaded from environment variables and .env file."""

import os
from dataclasses import dataclass, field
from typing import List

try:
    from dotenv import load_dotenv

    load_dotenv()
except Exception:
    pass


def _env(name: str, default: str) -> str:
    return os.getenv(name, default)


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except ValueError:
        return default


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    value = raw.strip().lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off"}:
        return False
    return default


def _autonomy_planner_mode() -> str:
    raw = os.getenv("AUTONOMY_PLANNER_MODE", "").strip().lower()
    if raw in {"deterministic", "auto", "ollama_required"}:
        return raw
    # Backward compatibility: old bool flag maps to deterministic/auto.
    if _env_bool("AUTONOMY_PLANNER_USE_OLLAMA", False):
        return "auto"
    return "deterministic"


@dataclass(frozen=True)
class Settings:
    host: str = _env("BACKEND_HOST", "0.0.0.0")
    port: int = _env_int("BACKEND_PORT", 8000)
    event_log_max: int = _env_int("EVENT_LOG_MAX", 1000)
    event_limit_default: int = _env_int("EVENT_LIMIT_DEFAULT", 200)
    summary_event_count: int = _env_int("SUMMARY_EVENT_COUNT", 20)
    db_path: str = _env("BACKEND_DB_PATH", "backend/data/desktopai.db")
    db_retention_days: int = _env_int("DB_RETENTION_DAYS", 14)
    db_max_events: int = _env_int("DB_MAX_EVENTS", 20000)
    db_max_autonomy_runs: int = _env_int("DB_MAX_AUTONOMY_RUNS", 2000)
    db_autonomy_retention_days: int = _env_int("DB_AUTONOMY_RETENTION_DAYS", 0)
    db_max_task_records: int = _env_int("DB_MAX_TASK_RECORDS", 5000)
    db_task_retention_days: int = _env_int("DB_TASK_RETENTION_DAYS", 0)

    llm_provider: str = _env("LLM_PROVIDER", "ollama")
    ollama_url: str = _env("OLLAMA_URL", "http://localhost:11434")
    ollama_model: str = _env("OLLAMA_MODEL", "llama3.1:8b")
    ollama_vision_model: str = _env("OLLAMA_VISION_MODEL", "")
    ollama_classifier_model: str = _env("OLLAMA_CLASSIFIER_MODEL", "")
    ollama_planner_model: str = _env("OLLAMA_PLANNER_MODEL", "")
    ollama_executor_model: str = _env("OLLAMA_EXECUTOR_MODEL", "")
    openai_api_key: str = _env("OPENAI_API_KEY", "")
    openai_base_url: str = _env("OPENAI_BASE_URL", "https://api.openai.com/v1")
    openai_model: str = _env("OPENAI_MODEL", "gpt-4o")
    autonomy_planner_mode: str = _autonomy_planner_mode()
    personality_mode: str = _env("PERSONALITY_MODE", "assistant")
    personality_auto_adapt: bool = _env_bool("PERSONALITY_AUTO_ADAPT", False)
    classifier_default: str = _env("CLASSIFIER_DEFAULT", "docs")
    classifier_use_ollama: bool = _env_bool("CLASSIFIER_USE_OLLAMA", False)
    action_executor_mode: str = _env("ACTION_EXECUTOR_MODE", "auto")
    action_executor_timeout_s: int = _env_int("ACTION_EXECUTOR_TIMEOUT_S", 20)
    action_executor_powershell: str = _env("ACTION_EXECUTOR_POWERSHELL", "powershell.exe")
    action_executor_default_compose_text: str = _env(
        "ACTION_EXECUTOR_DEFAULT_COMPOSE_TEXT",
        "Draft generated by DesktopAI.",
    )
    action_executor_retry_count: int = _env_int("ACTION_EXECUTOR_RETRY_COUNT", 2)
    action_executor_retry_delay_ms: int = _env_int("ACTION_EXECUTOR_RETRY_DELAY_MS", 150)
    action_executor_bridge_timeout_s: int = _env_int("BRIDGE_TIMEOUT_S", 20)
    vision_agent_max_iterations: int = _env_int("VISION_AGENT_MAX_ITERATIONS", 15)
    vision_agent_enabled: bool = _env_bool("VISION_AGENT_ENABLED", True)
    vision_agent_min_confidence: float = float(_env("VISION_AGENT_MIN_CONFIDENCE", "0.3"))
    vision_agent_max_consecutive_errors: int = _env_int("VISION_AGENT_MAX_CONSECUTIVE_ERRORS", 3)
    vision_agent_error_backoff_ms: int = _env_int("VISION_AGENT_ERROR_BACKOFF_MS", 500)
    trajectory_context_max_chars: int = _env_int("TRAJECTORY_CONTEXT_MAX_CHARS", 1500)
    trajectory_context_max_results: int = _env_int("TRAJECTORY_CONTEXT_MAX_RESULTS", 3)
    cdp_endpoint: str = _env("CDP_ENDPOINT", "http://localhost:9222")
    ui_telemetry_artifact_dir: str = _env("UI_TELEMETRY_ARTIFACT_DIR", "artifacts/ui/telemetry")
    ui_telemetry_max_events: int = _env_int("UI_TELEMETRY_MAX_EVENTS", 5000)
    runtime_log_max_entries: int = _env_int("RUNTIME_LOG_MAX_ENTRIES", 2000)
    api_token: str = _env("API_TOKEN", "")
    rate_limit_per_minute: int = _env_int("RATE_LIMIT_PER_MINUTE", 60)
    chat_memory_max_messages: int = _env_int("CHAT_MEMORY_MAX_MESSAGES", 100)
    chat_memory_max_conversations: int = _env_int("CHAT_MEMORY_MAX_CONVERSATIONS", 50)
    notifications_enabled: bool = _env_bool("NOTIFICATIONS_ENABLED", True)
    notification_idle_threshold_s: int = _env_int("NOTIFICATION_IDLE_THRESHOLD_S", 300)
    notification_max_count: int = _env_int("NOTIFICATION_MAX_COUNT", 200)
    ws_max_connections: int = _env_int("WS_MAX_CONNECTIONS", 50)
    collector_heartbeat_interval_s: int = _env_int("COLLECTOR_HEARTBEAT_INTERVAL_S", 30)

    allowed_origins: List[str] = field(
        default_factory=lambda: [
            origin.strip()
            for origin in _env("ALLOWED_ORIGINS", "").split(",")
            if origin.strip()
        ]
    )


settings = Settings()
