from __future__ import annotations

import os
import sqlite3
from datetime import datetime, timezone
from typing import Any, Dict

from .action_executor import build_action_executor
from .config import settings


def _is_memory_db_path(path: str) -> bool:
    value = (path or "").strip().lower()
    return value in {":memory:", "file::memory:"} or value.startswith("file::memory:")


def _sqlite_write_probe(path: str) -> None:
    uri = (path or "").strip().lower().startswith("file:")
    probe_table = f"selftest_probe_{int(datetime.now(timezone.utc).timestamp() * 1000000)}"
    conn = sqlite3.connect(path, uri=uri)
    try:
        cur = conn.cursor()
        cur.execute(f'CREATE TABLE "{probe_table}" (value TEXT NOT NULL)')
        cur.execute(
            f'INSERT INTO "{probe_table}" (value) VALUES (?)',
            (datetime.now(timezone.utc).isoformat(),),
        )
        cur.execute(f'DROP TABLE "{probe_table}"')
        conn.commit()
    finally:
        conn.close()


def run_selftest() -> Dict[str, Any]:
    """Cheap, local-only health/self-test.

    Goal: quickly answer "is the backend + persistence basically working?".
    This does NOT test the Windows collector.
    """

    checks: Dict[str, Any] = {}

    # DB path writable
    db_path = settings.db_path
    if _is_memory_db_path(db_path):
        checks["db_path_writable"] = {"ok": True, "path": db_path, "mode": "memory"}
    else:
        db_dir = os.path.dirname(db_path) or "."
        try:
            os.makedirs(db_dir, exist_ok=True)
            probe = os.path.join(db_dir, ".selftest-write")
            with open(probe, "w", encoding="utf-8") as f:
                f.write(datetime.now(timezone.utc).isoformat())
            os.remove(probe)
            checks["db_path_writable"] = {"ok": True, "path": db_path, "directory": db_dir}
        except Exception as e:
            checks["db_path_writable"] = {
                "ok": False,
                "path": db_path,
                "directory": db_dir,
                "error": str(e),
            }

    try:
        _sqlite_write_probe(db_path)
        checks["sqlite_probe"] = {"ok": True, "path": db_path}
    except Exception as e:
        checks["sqlite_probe"] = {"ok": False, "path": db_path, "error": str(e)}

    # Ollama reachability is tested via /api/ollama already; just surface config
    checks["ollama_config"] = {
        "ok": True,
        "url": settings.ollama_url,
        "model": settings.ollama_model,
    }

    try:
        executor = build_action_executor(
            mode=getattr(settings, "action_executor_mode", "auto"),
            powershell_executable=getattr(settings, "action_executor_powershell", "powershell.exe"),
            timeout_s=getattr(settings, "action_executor_timeout_s", 20),
            default_compose_text=getattr(
                settings,
                "action_executor_default_compose_text",
                "Draft generated by DesktopAI.",
            ),
        )
        status = executor.status()
        checks["action_executor"] = {
            "ok": bool(status.get("available", False) or status.get("mode") == "simulated"),
            "mode": status.get("mode"),
            "available": status.get("available"),
            "message": status.get("message"),
            "powershell": status.get("powershell"),
        }
    except Exception as e:
        checks["action_executor"] = {"ok": False, "error": str(e)}

    ok = all(v.get("ok") for v in checks.values())

    return {
        "ok": ok,
        "ts": datetime.now(timezone.utc).isoformat(),
        "checks": checks,
        "notes": [
            "This validates backend config + local filesystem writability.",
            "SQLite probe validates open/write/drop access for configured DB path.",
            "Collector connectivity must be tested separately (Windows).",
            "Real desktop action execution requires a Windows host; non-Windows hosts run simulated mode by default.",
        ],
    }
